/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class AckResponse extends Response {
  private long swigCPtr;

  protected AckResponse(long cPtr, boolean cMemoryOwn) {
    super(VSidoConnectJNI.AckResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AckResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VSidoConnectJNI.delete_AckResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AckResponse(SWIGTYPE_p_listT_unsigned_char_t uart, Request req) {
    this(VSidoConnectJNI.new_AckResponse(SWIGTYPE_p_listT_unsigned_char_t.getCPtr(uart), Request.getCPtr(req), req), true);
  }

  public String msg() {
    return VSidoConnectJNI.AckResponse_msg(swigCPtr, this);
  }

  public String JSON() {
    return VSidoConnectJNI.AckResponse_JSON(swigCPtr, this);
  }

}
