/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ComplianceRequest extends Request {
  private long swigCPtr;

  protected ComplianceRequest(long cPtr, boolean cMemoryOwn) {
    super(VSidoConnectJNI.ComplianceRequest_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ComplianceRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VSidoConnectJNI.delete_ComplianceRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ComplianceRequest() {
    this(VSidoConnectJNI.new_ComplianceRequest(), true);
  }

  public void comp(short sid, short cp1, short cp2) {
    VSidoConnectJNI.ComplianceRequest_comp(swigCPtr, this, sid, cp1, cp2);
  }

}
