/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class MinMaxAngleRequest extends Request {
  private long swigCPtr;

  protected MinMaxAngleRequest(long cPtr, boolean cMemoryOwn) {
    super(VSidoConnectJNI.MinMaxAngleRequest_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MinMaxAngleRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VSidoConnectJNI.delete_MinMaxAngleRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MinMaxAngleRequest() {
    this(VSidoConnectJNI.new_MinMaxAngleRequest(), true);
  }

  public void minMax(short sid, int min, int max) {
    VSidoConnectJNI.MinMaxAngleRequest_minMax(swigCPtr, this, sid, min, max);
  }

}
