/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ServoInfoRequest extends Request {
  private long swigCPtr;

  protected ServoInfoRequest(long cPtr, boolean cMemoryOwn) {
    super(VSidoConnectJNI.ServoInfoRequest_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServoInfoRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VSidoConnectJNI.delete_ServoInfoRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ServoInfoRequest() {
    this(VSidoConnectJNI.new_ServoInfoRequest(), true);
  }

  public void info(short sid, short address, short length) {
    VSidoConnectJNI.ServoInfoRequest_info(swigCPtr, this, sid, address, length);
  }

}
