/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ServoInfoResponse extends Response {
  private long swigCPtr;

  protected ServoInfoResponse(long cPtr, boolean cMemoryOwn) {
    super(VSidoConnectJNI.ServoInfoResponse_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ServoInfoResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        VSidoConnectJNI.delete_ServoInfoResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ServoInfoResponse(SWIGTYPE_p_listT_unsigned_char_t uart, Request req) {
    this(VSidoConnectJNI.new_ServoInfoResponse(SWIGTYPE_p_listT_unsigned_char_t.getCPtr(uart), Request.getCPtr(req), req), true);
  }

  public String JSON() {
    return VSidoConnectJNI.ServoInfoResponse_JSON(swigCPtr, this);
  }

  public SWIGTYPE_p_mapT_unsigned_char_listT_tupleT_std__string_int_t_t_t info() {
    return new SWIGTYPE_p_mapT_unsigned_char_listT_tupleT_std__string_int_t_t_t(VSidoConnectJNI.ServoInfoResponse_info(swigCPtr, this), true);
  }

}
