/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class VSidoConnect {
  public static void connect(String dist) {
    VSidoConnectJNI.connect__SWIG_0(dist);
  }

  public static void connect() {
    VSidoConnectJNI.connect__SWIG_1();
  }

  public static void disConnect() {
    VSidoConnectJNI.disConnect();
  }

  public static String execWithJsonResult(Request req) {
    return VSidoConnectJNI.execWithJsonResult(Request.getCPtr(req), req);
  }

}
