/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class VSidoConnectJNI {
  public final static native void connect__SWIG_0(String jarg1);
  public final static native void connect__SWIG_1();
  public final static native void disConnect();
  public final static native void delete_Request(long jarg1);
  public final static native String execWithJsonResult(long jarg1, Request jarg1_);
  public final static native long new_AngleRequest();
  public final static native void AngleRequest_cycle(long jarg1, AngleRequest jarg1_, int jarg2);
  public final static native void AngleRequest_angle(long jarg1, AngleRequest jarg1_, short jarg2, int jarg3);
  public final static native void delete_AngleRequest(long jarg1);
  public final static native long new_ComplianceRequest();
  public final static native void ComplianceRequest_comp(long jarg1, ComplianceRequest jarg1_, short jarg2, short jarg3, short jarg4);
  public final static native void delete_ComplianceRequest(long jarg1);
  public final static native long new_MinMaxAngleRequest();
  public final static native void MinMaxAngleRequest_minMax(long jarg1, MinMaxAngleRequest jarg1_, short jarg2, int jarg3, int jarg4);
  public final static native void delete_MinMaxAngleRequest(long jarg1);
  public final static native long new_ServoInfoRequest();
  public final static native void ServoInfoRequest_info(long jarg1, ServoInfoRequest jarg1_, short jarg2, short jarg3, short jarg4);
  public final static native void delete_ServoInfoRequest(long jarg1);
  public final static native String Response_JSON(long jarg1, Response jarg1_);
  public final static native void delete_Response(long jarg1);
  public final static native long new_AckResponse(long jarg1, long jarg2, Request jarg2_);
  public final static native String AckResponse_msg(long jarg1, AckResponse jarg1_);
  public final static native String AckResponse_JSON(long jarg1, AckResponse jarg1_);
  public final static native void delete_AckResponse(long jarg1);
  public final static native long new_ServoInfoResponse(long jarg1, long jarg2, Request jarg2_);
  public final static native String ServoInfoResponse_JSON(long jarg1, ServoInfoResponse jarg1_);
  public final static native long ServoInfoResponse_info(long jarg1, ServoInfoResponse jarg1_);
  public final static native void delete_ServoInfoResponse(long jarg1);
  public final static native long AngleRequest_SWIGUpcast(long jarg1);
  public final static native long ComplianceRequest_SWIGUpcast(long jarg1);
  public final static native long MinMaxAngleRequest_SWIGUpcast(long jarg1);
  public final static native long ServoInfoRequest_SWIGUpcast(long jarg1);
  public final static native long AckResponse_SWIGUpcast(long jarg1);
  public final static native long ServoInfoResponse_SWIGUpcast(long jarg1);
}
