/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_VSIDOCONNECT_H
#define PHP_VSIDOCONNECT_H

extern zend_module_entry VSidoConnect_module_entry;
#define phpext_VSidoConnect_ptr &VSidoConnect_module_entry

#ifdef PHP_WIN32
# define PHP_VSIDOCONNECT_API __declspec(dllexport)
#else
# define PHP_VSIDOCONNECT_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(VSidoConnect);
PHP_MSHUTDOWN_FUNCTION(VSidoConnect);
PHP_RINIT_FUNCTION(VSidoConnect);
PHP_RSHUTDOWN_FUNCTION(VSidoConnect);
PHP_MINFO_FUNCTION(VSidoConnect);

ZEND_NAMED_FUNCTION(_wrap_connect);
ZEND_NAMED_FUNCTION(_wrap_disConnect);
ZEND_NAMED_FUNCTION(_wrap_execWithJsonResult);
ZEND_NAMED_FUNCTION(_wrap_new_AngleRequest);
ZEND_NAMED_FUNCTION(_wrap_AngleRequest_cycle);
ZEND_NAMED_FUNCTION(_wrap_AngleRequest_angle);
ZEND_NAMED_FUNCTION(_wrap_new_ComplianceRequest);
ZEND_NAMED_FUNCTION(_wrap_ComplianceRequest_comp);
ZEND_NAMED_FUNCTION(_wrap_new_MinMaxAngleRequest);
ZEND_NAMED_FUNCTION(_wrap_MinMaxAngleRequest_minMax);
ZEND_NAMED_FUNCTION(_wrap_new_ServoInfoRequest);
ZEND_NAMED_FUNCTION(_wrap_ServoInfoRequest_info);
ZEND_NAMED_FUNCTION(_wrap_Response_JSON);
ZEND_NAMED_FUNCTION(_wrap_new_AckResponse);
ZEND_NAMED_FUNCTION(_wrap_AckResponse_msg);
ZEND_NAMED_FUNCTION(_wrap_AckResponse_JSON);
ZEND_NAMED_FUNCTION(_wrap_new_ServoInfoResponse);
ZEND_NAMED_FUNCTION(_wrap_ServoInfoResponse_JSON);
ZEND_NAMED_FUNCTION(_wrap_ServoInfoResponse_info);
#endif /* PHP_VSIDOCONNECT_H */
